### ISSUE TITLE
Django server error unresolved paths when DEBUG=False

### ISSUE THREAD

**Issue by KevinThePepper** [ASU-CodeDevils/sso.codedevils.org#9]
The website works great when `DEBUG = True`. As soon as I turn `DEBUG = False` I receive this recursive error message followed by the server crashing saying `A server error occurred. Please contact the administrator` (this varies based on where I'm testing but basically saying the response was incomplete).

```
WARNING 2020-11-01 08:36:43,217 loader_tags 17863 123145445117952 Exception raised while rendering {% include %} for template '404.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLResolver list> (None:None) 'en-us/'>], [<URLResolver <module 'config.api_router' from '/Users/kevin/projects/cdsso/config/api_router.py'> (api:api) 'api/'>]], 'path': 'join/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/core/handlers/exception.py", line 99, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/views/defaults.py", line 46, in page_not_found
    body = template.render(context, request)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/template/defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/kevin/projects/.envs/cdsso/lib/python3.7/site-packages/django/urls/resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
```

It repeats that `django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found` repeatedly until it crashes. Here's a [link to the base settings file](https://github.com/ASU-CodeDevils/sso.codedevils.org/blob/master/config/settings/base.py) and [the base url file](https://github.com/ASU-CodeDevils/sso.codedevils.org/blob/master/config/urls.py). So far I have tried:

 - Removing the `i18n_patterns` from `urls.py`. I still received the error on pages not found or cached.
 - Adding `DEBUG_PROPAGATE_EXCEPTIONS = True`. This simply stops the recursion, but the same error message shows.
 - Changing the `STATIC_ROOT` and `STATICFILES_DIRS` to a different directory. I didn't think this was the issue since it was simply not registering my urls, and had no indication of any missing static assets.

**Comment by KevinThePepper** [comment]
[Uploading error.log…]()

**Comment by KevinThePepper** [comment]
[error.log](https://github.com/ASU-CodeDevils/sso.codedevils.org/files/5472867/error.log)

**Comment by KevinThePepper** [comment]
Ended up being an error with the custom error templates. Fixed by extending the appropriate base template and changing the link to the buttons.
